C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*P(2,1) - P(-1,1)*P(-1,2)*Metric(1,2)
C     
      SUBROUTINE VVSS4_0(V1, V2, S3, S4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 TMP2
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP1
      REAL*8 P1(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 TMP0
      REAL*8 P2(0:3)
      COMPLEX*16 VERTEX
      COMPLEX*16 COUP,FFBOX1,ftri
      COMPLEX*16 V1(*)
      COMPLEX*16 TMP3
      COMPLEX*16 S4(*)
      include '../coupl.inc'
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      P3(0) = -DBLE(S3(1))
      P3(1) = -DBLE(S3(2))
      P3(2) = -DIMAG(S3(2))
      P3(3) = -DIMAG(S3(1))
      TMP1 = (V1(3)*P2(0)-V1(4)*P2(1)-V1(5)*P2(2)-V1(6)*P2(3))
      TMP0 = (V2(3)*P1(0)-V2(4)*P1(1)-V2(5)*P1(2)-V2(6)*P1(3))
      TMP3 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      TMP2 = (V2(3)*V1(3)-V2(4)*V1(4)-V2(5)*V1(5)-V2(6)*V1(6))

      call GGHHformfactor2(p1,p2,p3,ffbox1,ftri)

      VERTEX = COUP*S3(3)*S4(3)*(-CI*(TMP0*TMP1)+CI*(TMP2*TMP3))*
     & 2d0*ftri
      END

      subroutine GGHHformfactor2(p1,p2,p3,fbox,ftri)
c****************************************************************************
c From the paper: Plehn, Spira & Zerwas, hep-ph/9603205
c scalar integrals (INISCAL subroutine) are directly copied
c from the 'hpair' program, see: http://people.web.psi.ch/spira/hpair/
c****************************************************************************
      implicit none

c Momenta of particles in event
c      include '../genps.inc'
   
      REAL*8 P1(0:3),P2(0:3),p3(0:3)
      double precision ff,sumdot,s,r,u,t,mq,mq2,ss,tt,uu,m1,m2
      double precision rho1,rho2,tauQ,tt1,uu1,tt2,uu2,epm
      double complex c03,d04,cq2,ca5
      double complex c0ab,c0ac,c0ad,c0bc,c0bd,c0cd
      double complex d0abc,d0bac,d0acb
      double complex fbox,ftri
      double precision Q1S,Q2S,q1,q2
      external sumdot,c03,d04
      INCLUDE '../coupl.inc'
      
      s=(p1(0)+p2(0))**2-
     & (p1(1)+p2(1))**2-(p1(2)+p2(2))**2-(p1(3)+p2(3))**2
      t=(p1(0)-p3(0))**2-
     & (p1(1)-p3(1))**2-(p1(2)-p3(2))**2-(p1(3)-p3(3))**2
      u=(p2(0)-p3(0))**2-
     & (p2(1)-p3(1))**2-(p2(2)-p3(2))**2-(p2(3)-p3(3))**2
      Q1s=p3(0)**2-p3(1)**2-p3(2)**2-p3(3)**2
      Q2s=(p1(0)+p2(0)-p3(0))**2-(p1(1)+p2(1)-p3(1))**2-(p1(2)+p2(2)
     & -p3(2))**2-(p1(3)+p2(3)-p3(3))**2     
      Q1=dsqrt(q1S)
      Q2=dsqrt(q2S)
      mQ2=MDL_MT**2
      ss=s/mQ2
      tt=t/mQ2
      uu=u/mQ2
      rho1=Q1S/mQ2
      rho2=Q2S/mQ2
      tauQ=4d0/ss
      tt1=tt-rho1
      uu1=uu-rho1
      tt2=tt-rho2
      uu2=uu-rho2
      
      call INISCAL(MDL_MT,S,T,U,Q1,Q2,
     &     C0AB,C0AC,C0AD,C0BC,C0BD,C0CD,D0ABC,D0BAC,D0ACB)

      C0AB = C0AB/MQ2
      C0AC = C0AC/MQ2
      C0AD = C0AD/MQ2
      C0BC = C0BC/MQ2
      C0BD = C0BD/MQ2
      C0CD = C0CD/MQ2


      D0ABC = D0ABC/MQ2**2
      D0BAC = D0BAC/MQ2**2
      D0ACB = D0ACB/MQ2**2

      Fbox= 1d0/ss**2*(4d0*ss+8d0*ss*mq2*c0ab
     &     -2d0*ss*(ss+rho1+rho2-8d0)*mQ2**2*(d0abc+d0bac+d0acb)
     &   +(rho1+rho2-8d0)*mq2*(tt1*c0ac+uu1*c0bc+uu2*c0ad+tt2*c0bd-
     &     (tt*uu-rho1*rho2)*mq2*d0acb))
    
      Ftri= 2d0/ss*(2d0+(4d0-ss)*mQ2*c0ab)  

      return
      end
